### ISSUE TITLE
Issue with plantuml and commit dc6bcb6

### ISSUE THREAD

**Issue by neilinger** [mabels/construqt#6]
Hi,

Since commit dc6bcb6 'ruby const.rb plantuml' throws this exception:
```
construqt/lib/construqt/flavour/plantuml/plantuml.rb:136:in `render_object_address': undefined method `each_with_index' for #<Construqt::Addresses::Address::Routes:0x007fd1430eff58> (NoMethodError)
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:99:in `draw'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:105:in `block in draw'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:104:in `each'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:104:in `draw'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:405:in `block (2 levels) in call'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:403:in `each'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:403:in `block in call'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:469:in `call'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:469:in `call'
	from /xxx/construqt/lib/construqt/flavour/flavour.rb:91:in `block in call_aspects'
	from /xxx/construqt/lib/construqt/flavour/flavour.rb:91:in `each'
	from /xxx/construqt/lib/construqt/flavour/flavour.rb:91:in `call_aspects'
	from /xxx/construqt/lib/construqt/hosts.rb:98:in `commit'
	from /xxx/construqt/lib/construqt.rb:95:in `block in produce'
	from /xxx/construqt/lib/construqt.rb:92:in `each'
	from /xxx/construqt/lib/construqt.rb:92:in `produce'
	from const.rb:52:in `<main>'
```

**Comment by mabels** [comment]
Hopefully fixed

dc629cfd8269367b37df08c5f15a620e20b7f87b

Meno
