### ISSUE TITLE
different plantuml exception after dc629cf

### ISSUE THREAD

**Issue by neilinger** [mabels/construqt#7]
After commit dc629cf the exception changed to this:
```
/Users/xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:145:in `sort': comparison of Array with String failed (ArgumentError)
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:145:in `render_object_address'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:99:in `draw'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:105:in `block in draw'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:104:in `each'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:104:in `draw'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:405:in `block (2 levels) in call'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:403:in `each'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:403:in `block in call'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:469:in `call'
	from /xxx/construqt/lib/construqt/flavour/plantuml/plantuml.rb:469:in `call'
	from /xxx/construqt/lib/construqt/flavour/flavour.rb:91:in `block in call_aspects'
	from /xxx/construqt/lib/construqt/flavour/flavour.rb:91:in `each'
	from /xxx/construqt/lib/construqt/flavour/flavour.rb:91:in `call_aspects'
	from /xxx/construqt/lib/construqt/hosts.rb:98:in `commit'
	from /xxx/construqt/lib/construqt.rb:96:in `block in produce'
	from /xxx/construqt/lib/construqt.rb:93:in `each'
	from /xxx/construqt/lib/construqt.rb:93:in `produce'
	from const.rb:94:in `<main>'
```

**Comment by mabels** [comment]
Which config you use. I test with s2b, no problem.

Meno

**Comment by neilinger** [comment]
Latest of s2b/s2d.rb, doesn't work :(

**Comment by mabels** [comment]
I will recheck it.

thx

meno

**Comment by mabels** [comment]
Hopefully now it works again.

There was a condition that the tag list does not contain just strings, in this case there was
it a array of strings.

meno

e2ab3cb6180e4a62671571349e6c6753e2bb8eb1
